### ISSUE TITLE
Generalize `wait_for_postgres`

### ISSUE THREAD

**Issue by smithjd** [smithjd/sqlpetr#5]
**Is your feature request related to a problem? Please describe.**
Why restrict as suggested  here https://github.com/smithjd/sqlpetr/blob/master/R/wait_for_postgres.R to `This function is used during development`?

**Describe the solution you'd like**
We could add a parameter with a default:

  `host = "localhost"`

**Comment by znmeb** [comment]
Within a script accessing a single PostgreSQL service, the most common pattern is to define a connection string as a single parameter. The connection string includes host, port, database name to connect to, role to connect as, and password. Since the password is a secret, the connection string should never be visible.

If you have more than one connection string, you'd need to manage them.

**Comment by smithjd** [comment]
What I'm talking about is a function that you can use to *generate* a connection without having to fiddle with the syntax.  And being able to use the same function in an informal or experimental setting and then going ahead and using it in more of a *production* setup.
